# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgWV87PHtR_oDG4b6adHAAgVx980Ri3X
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Set visualization style
sns.set(style="whitegrid")

# 1. LOAD AND PREPARE DATA
try:
    df_similar = pd.read_csv('SimilarIntersections_Cleaned.csv') # Corrected filename
    df_roundabouts = pd.read_csv('Roundabouts_Cleaned.csv')
except FileNotFoundError:
    print("Error: CSV files not found. Please ensure they are in the current directory.")

# Tag the intersection types
df_similar['Type'] = 'Non-Roundabout'
df_roundabouts['Type'] = 'Roundabout'

# Merge the datasets
df_all = pd.concat([df_similar, df_roundabouts], ignore_index=True)

# Remove rows where income data is missing
df_all = df_all.dropna(subset=['Median_HH_Income'])


# 2. INCOME CLASSIFICATION
# Using the specific median threshold provided
MEDIAN_INCOME_THRESHOLD = 71149

def classify_income(income):
    if income >= MEDIAN_INCOME_THRESHOLD:
        return 'High Income'
    else:
        return 'Low Income'

df_all['Income_Group'] = df_all['Median_HH_Income'].apply(classify_income)

# 3. DEFINE SPECIFIC FACTORS
target_factors = [
    'rate_NO_FACTOR',
    'rate_DISTRACTED',
    'rate_DRUG',
    'rate_ALCOHOL',
    'rate_SPEEDING',
    'rate_HITNRUN'
]

print(f"Generating plots for {len(target_factors)} specific safety factors...\n")

# 4. GENERATE FIGURES

for factor in target_factors:
    # Initialize a new figure
    plt.figure(figsize=(10, 6))

    # Generate the Bar Chart
    chart = sns.barplot(
        x='Type',
        y=factor,
        hue='Income_Group',
        data=df_all,
        palette={'Low Income': '#d9534f', 'High Income': '#5cb85c'}, # Red vs Green
        errorbar=None
    )

    # Clean up the label name for the title (e.g., "rate_HITNRUN" -> "Hitnrun")
    clean_name = factor.replace('rate_', '').replace('_', ' ').title()

    # Formatting
    plt.title(f'Analysis of {clean_name}\n(Based on Income Threshold: ${MEDIAN_INCOME_THRESHOLD:,})', fontsize=14)
    plt.ylabel(f'{clean_name} Rate (per Million Entering Vehicles)', fontsize=12)
    plt.xlabel('Intersection Type', fontsize=12)
    plt.legend(title='Socioeconomic Status')

    # Print statistics to the console for verification
    avg_rates = df_all.groupby(['Type', 'Income_Group'])[factor].mean()
    print(f"--- Average {clean_name} Rate ---")
    print(avg_rates)
    print("")

    plt.tight_layout()
    plt.show()